managers:
  - name: version
    configuration:
      maintainers:
        - HumairAK
        - tumido
        - 4n4nd
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
