#!/bin/bash
# Script to clone from github.com/operate-first/ and setup the environment
# (C) 2021 Karsten Wade <kwade@redhat.com> <quaid@iquaid.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# This barebones script is not very clever, because it is just trying to
# clone a repo and set it up according to Operate First community practices:
# https://URL_FOR_COMMUNITY_PRACTICES_NEEDED
#
# Use:
# ./o1-tools/bin/o1-clone repo-name
#
# For example:
# ./o1-tools/bin/o1-clone community-handbook
#
#
# Let's presume you want something from the /operate-first/ org and take in
# the first bash variable as the repo name:
git clone git@github.com:operate-first/$1.git
# Enter the project to prepare the environment
cd $1
# Install pre-commit hooks and whatever else it does
pre-commit install
#
# That's it for now, what other environment activities could we do here?
