#!/bin/sh

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail

# In CI test changes only
if [ ! -z "$PULL_BASE_SHA" ] && [ ! -z "$PULL_PULL_SHA" ]; then
    echo "Checking changes in range $PULL_BASE_SHA..$PULL_PULL_SHA only."
    bases=$(git diff --name-status $PULL_BASE_SHA $PULL_PULL_SHA | grep -Po "^[^D]\w*\W*\K.*?(?=/)" | sort | uniq)
else
    echo "Checking all overlays."
    bases="."
fi

# Let's ignore the secrets...

export KUSTOMIZE_PLUGIN_HOME=/tmp/new_plugin_dir

mkdir -p $KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/
echo '#!/bin/sh' >$KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/ksops
chmod +x $KUSTOMIZE_PLUGIN_HOME/viaduct.ai/v1/ksops/ksops

# and check all the sub directories with manifests...
k=$(for i in $(echo "$bases"); do find $i -regex ".*/overlays/.*kustomization.yaml"; done)

for d in $k; do
    if [[ $(dirname $d) == *odh-manifests* ]]; then
        echo skipping $(dirname $d)
        continue
    fi

    echo checking $(dirname $d)
    kustomize build --enable-alpha-plugins $(dirname $d) 2>&1 >/dev/null
done

#end.
