#!/bin/sh

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail

conftest test --trace --policy policy/argocd_app.rego **/*.yaml

#end.
